export enum FlowPairsColumnsNames {
  Status = 'Status',
  Site = 'Site',
  ServerSite = 'Server Site',
  Server = 'Server',
  Client = 'Client',
  From = 'From',
  To = 'To',
  TxBytes = 'Tx Data',
  RxBytes = 'Rx Data',
  TxByteRate = 'Tx Rate',
  RxByteRate = 'Rx Rate',
  TxLatency = 'Tx Latency',
  RxLatency = 'Rx Latency',
  Latency = 'latency',
  TTFB = 'TTFB',
  RequestCompleted = 'Completed',
  Duration = 'Duration',
  Host = 'Host',
  Port = 'Port',
  ClientPort = 'Client Port',
  ServerPort = 'Server Port',
  Method = 'Method',
  StatusCode = 'Status',
  Trace = 'Trace'
}
