export enum FlowPairsColumnsNames {
    Status = 'Status',
    Site = 'Site',
    ServerSite = 'Server Site',
    Server = 'Server',
    Client = 'Client',
    From = 'From',
    To = 'To',
    BytesTx = 'Tx Bytes',
    BytesRx = 'Rx Bytes',
    UploadRate = 'Speed Request ',
    DownloadRate = 'Speed Response',
    ByteRateTX = 'Speed In',
    ByteRateRX = 'Speed Out',
    DownloadLatency = 'Latency Response',
    UploadLatency = 'Latency Request',
    RequestCompleted = 'Completed',
    Duration = 'Duration',
    Host = 'Host',
    Port = 'Port',
    Method = 'Method',
    StatusCode = 'Status',
    Trace = 'Trace',
}
