export enum Labels {
    Devices = 'Clients & Servers',
    Flows = 'Log of service flows',
    NoFlows = 'Please select a Client or Server to show the associated flows',
    NoResult = 'No flows found',
}

export enum DetailsColumnsNames {
    To = 'To',
    Hostname = 'Hostname',
    Name = 'Source',
    Direction = 'Direction',
    Namespace = 'Namespace',
    Site = 'Site',
    TargetSite = 'Target Site',
    Protocol = 'Protocol',
    Router = 'Router',
    TargetRouter = 'Target Router',
    TargetDirection = 'Target Direction',
    DestinationHost = 'Host',
    DestinationPort = 'Port',
    Status = 'Status',
    Type = 'Type',
    ConnectionStatus = 'Status',
    Connections = 'Connections',
    IP = 'Source IP',
    Port = 'Port',
    Traffic = 'Traffic',
    TrafficIn = 'Traffic',
    Latency = 'Latency',
    LatencyIn = 'Latency',
    StartTime = 'Created at',
}
