export enum BiFlowListLabels {
  Port = 'Port',
  Method = 'Method',
  ByteRate = 'Byte rate',
  Duration = 'Duration',
  Site = 'Client Site',
  ServerSite = 'Server site',
  Server = 'Server',
  Client = 'Client',
  From = 'From client',
  To = 'To server',
  TxBytes = 'Data Out',
  RxBytes = 'Data In',
  TxByteRate = 'Rate Out',
  RxByteRate = 'Rate In',
  TxLatency = 'Latency Out',
  RxLatency = 'Latency In',
  Completed = 'Completed',
  StatusCode = 'Status',
  Open = 'Open',
  Closed = 'Closed',
  Terminated = 'Terminated'
}
