export enum ProcessesRoutesPaths {
  Processes = '/processes'
}

export enum QueriesProcesses {
  GetProcessesPaginated = 'get-processes-paginated-query',
  GetRemoteProcessesPaginated = 'get-remote-processes-paginated-query',
  GetProcesses = 'get-processes-query',
  GetProcess = 'get-process-query',
  GetProcessResult = 'get-process-result-query',
  GetSource = 'get-process-query',
  GetDestination = 'get-destination-process-query',
  GetProcessPairs = 'get-process-pairs',
  GetProcessPair = 'get-process-pair',
  GetProcessPairsResult = 'get-process-pairs-result',
  GetBiFlows = 'get-process-bi-flows',
  GetBiFlow = 'get-process-bi-flow',
  GetHttp = 'get-process-http-pairs',
  GetServicesByProcessId = 'get-services-by-process-id-query'
}

export enum ProcessesLabels {
  Section = 'Processes',
  Overview = 'Overview',
  Description = 'A process represents running application code. On Kubernetes, a process is a pod. On Docker or Podman, a process is a container. On virtual machines or bare metal hosts',
  Details = 'Details',
  ProcessPairs = 'Pairs',
  Processes = 'Processes',
  Services = 'Routing keys',
  Process = 'Process',
  Site = 'Site',
  ProcessGroup = 'Component',
  Image = 'Image',
  Created = 'Created',
  SourceIP = 'IP',
  Host = 'Host',
  TrafficInOutDistribution = 'Traffic distribution',
  ChartProcessLatencySeriesAxisYLabel = 'Latency',
  RequestsPerSecondsSeriesAxisYLabel = 'Request rate',
  ErrorRateSeriesAxisYLabel = 'Error rate',
  Clients = 'Clients',
  Servers = 'Servers',
  Http2Requests = 'Http2 requests',
  HttpRequests = 'Http requests',
  ExposedTitle = 'Exposure status',
  IsExposed = 'Exposed',
  IsNotExposed = 'Unexposed',
  OpenConnections = 'Open connections',
  OldConnections = 'Connection history',
  ProcessPairsEmptyTitle = 'No connections or requests to display',
  ProcessPairsEmptyMessage = 'As new connections or requests are established, they will be dynamically added to the table for display',
  GoToDetailsLink = 'View details',
  Title = 'Pair details',
  Protocol = 'Protocol',
  TransportProtocol = 'Transport protocol',
  ApplicationProtocols = 'Application protocols',
  Bytes = 'Bytes',
  ByteRate = 'Byterate',
  Latency = 'Latency',
  Name = 'Name',
  Component = 'Component',
  ByteRateRx = 'Byte rate In',
  Exposed = 'Exposed'
}
